name: Build Mobile

on:
   workflow_dispatch:

jobs:
  develop-build:
    uses: JoshCarter-ops/reusable/.github/workflows/build-mobile.yml@main
    with:
      branch_name: main
      environment: develop
      node_version: '16'
    secrets:
      AWS_ROLE: "DEFAULTING"
      ARTIFACT_S3: "DEFAULTING"
      KEYCHAIN_PASSWORD: "DEFAULTING"
      APPLE_DEVELOPER_TEAM: "DEFAULTING"
      APPLE_DEVELOPER_EMAIL: "DEFAULTING"
      APPLE_DEVELOPER_PASSWORD: "DEFAULTING"

  integration-build:
    uses: JoshCarter-ops/reusable/.github/workflows/build-mobile.yml@main
    with:
      branch_name: main
      environment: integration
      node_version: '18'
    secrets:
      AWS_ROLE: "DEFAULTING"
      ARTIFACT_S3: "DEFAULTING"
      KEYCHAIN_PASSWORD: "DEFAULTING"
      APPLE_DEVELOPER_TEAM: "DEFAULTING"
      APPLE_DEVELOPER_EMAIL: "DEFAULTING"
      APPLE_DEVELOPER_PASSWORD: "DEFAULTING"
