name: Share data
on: workflow_dispatch
jobs:
  data-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log

# to do this in the same workflow you can add the "needs: data-job" to the next job to get it to work commented out as it is an example
  # get-data-job:
  #   runs-on: ubuntu-latest
  #   needs: data-job
  #   steps:
  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #        name: output-log-file