# This will pull the aretfact from the get_data job
name: Get data
on: workflow_dispatch
jobs:
    get-data-job:
      runs-on: ubuntu-latest
      steps:
        - name: Download a single artifact
          uses: actions/download-artifact@v3
          with:
            name: output-log-file