# This file will confirm your configuration is running correctly
# It will spin up a docker container and execute the commands you supply
# !! Please create your own branch to test this out, don't push to main !!

name: Hello World!
on: workflow_dispatch
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello World, I'm running!"

  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi!
        run: echo "Hi World, I'm running!"