name: Publish to GitHub Pages
on: workflow_dispatch
permissions:
    id-token: write
    contents: write

jobs:
  generate-html:
    name: Generate HTML and Directories
    runs-on: ubuntu-latest
    steps:
        - name: Get Code
          uses: actions/checkout@v3
        
        - name: Generate HTML for Pages
          run: |
            sed -i'' -e 's/RUN_ID/${{ github.run_id }}/g' page.html
            cat page.html
        
        - name: Copy into Deployments Dir
          run: |
            mkdir -p deployments/${{ github.run_id }}
            cp page.html deployments/${{ github.run_id }}/
            ls -lah deployments

        - name: Add Lastest Run to Listing
          run: echo 'https://joshcarter-ops.github.io/actions-practice/${{github.run_id}}/page.html' >> index.html
        
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./deployments
            publish_branch: gh-pages
            keep_files: true
