name: Use Secret Example
on: workflow_dispatch
jobs:
  top-secret-job:
    runs-on: ubuntu-latest
    steps:
        - name: Environment
          run: echo "This is an Environment Variable Value ${{ env.VALUE_FROM_ENV }}"
        - name: Secret
          run: echo "This is a Secret Variable Value ${{ secrets.MY_SECRET }}"
