name: Variables Example
on: workflow_dispatch
jobs:
  variables:
    runs-on: ubuntu-latest
    env: 
        STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
        LAST_NAME: Smith
    steps:
      - name: Example with Environment Variable Setting
        run: |
            echo 'FIRST_NAME=John' >> $GITHUB_ENV
            echo 'This job was written by: ${{ env.GITHUB_REPOSITORY_OWNER }}'
      - name: Print Variable
    #   Here we will get a variable set from a command above, the env section for job specific variables and the .env file
        run: echo "Environment says that you are - $FIRST_NAME $LAST_NAME from the $PLACE"
      - name: Print Stage
        run: 
            echo "${{ env.STAGE }}"